version: '3.8'

services:
  user-mariadb:
    image: mariadb:10.6
    container_name: user-mariadb
    environment:
      MARIADB_ROOT_PASSWORD: $USER_MARIADB_PASSWORD
      MARIADB_DATABASE: $USER_MARIADB_NAME
      MARIADB_USER: $USER_MARIADB_USERNAME
      MARIADB_PASSWORD: $USER_MARIADB_PASSWORD
    ports:
      - $USER_MARIADB_PORT:3306

  user-redis:
    image: redis:7
    container_name: user-redis
    ports:
      - $USER_REDIS_PORT:6379
    command: >
      redis-server --requirepass $USER_REDIS_PASSWORD

  product-mongodb:
    image: mongo
    container_name: product-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: $PRODUCT_MONGODB_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $PRODUCT_MONGODB_PASSWORD
      MONGO_INITDB_DATABASE: $PRODUCT_MONGODB_NAME
    ports:
      - $PRODUCT_MONGODB_PORT:27017

  cart-mongodb:
    image: mongo
    container_name: cart-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: $CART_MONGODB_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $CART_MONGODB_PASSWORD
      MONGO_INITDB_DATABASE: $CART_MONGODB_NAME
    ports:
      - $CART_MONGODB_PORT:27017

  sale-mongodb:
    image: mongo
    container_name: sale-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: $SALE_MONGODB_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $SALE_MONGODB_PASSWORD
      MONGO_INITDB_DATABASE: $SALE_MONGODB_NAME
    ports:
      - $SALE_MONGODB_PORT:27017
