version: '3.8'

services:
  mariadb:
    image: mariadb:10.6
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: $MARIADB_PASSWORD
      MARIADB_DATABASE: $MARIADB_NAME
      MARIADB_USER: $MARIADB_USERNAME
      MARIADB_PASSWORD: $MARIADB_PASSWORD
    ports:
      - $MARIADB_PORT:3306

  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_IMAGE_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_IMAGE_PASSWORD
      MONGO_INITDB_DATABASE: $MONGODB_IMAGE_NAME
    ports:
      - $MONGODB_IMAGE_PORT:27017

  redis:
    image: redis:7
    container_name: redis
    ports:
      - $REDIS_PORT:6379
    command: >
      redis-server --requirepass $REDIS_PASSWORD
