name: Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version: "20"
      - name: Install dependencies
        run: cd ./packages/api && npm install
      - name: Lint
        run: cd ./packages/api && npm run lint

  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version: "20"
      - name: Install dependencies
        run: cd ./packages/api && npm install
      - name: Build
        run: cd ./packages/api && npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  test:
    needs: [lint, build]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version: "20"
      - name: Install dependencies
        run: cd ./packages/api && npm install
      - name: Test
        run: cd ./packages/api && npm run test

  test-e2e:
    needs: [lint, build]
    runs-on: ubuntu-20.04
    services:
      mariadb:
        image: mariadb:10.6
        env:
          MARIADB_ROOT_PASSWORD: ${{ secrets.MARIADB_PASSWORD_TEST }}
          MARIADB_DATABASE: ${{ secrets.MARIADB_NAME_TEST }}
          MARIADB_USER: ${{ secrets.MARIADB_USERNAME_TEST }}
          MARIADB_PASSWORD: ${{ secrets.MARIADB_PASSWORD_TEST }}
        ports:
          - 3306:3306
      mongodb:
        image: mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGODB_IMAGE_USERNAME_TEST }}
          MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGODB_IMAGE_PASSWORD_TEST }}
          MONGO_INITDB_DATABASE: ${{ secrets.MONGODB_IMAGE_NAME_TEST }}
        ports:
          - 27017:27017
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version: "20"
      - name: Install dependencies
        run: |
          cd ./packages/api
          echo "MARIADB_NAME=${{ secrets.MARIADB_NAME_TEST }}" >> .env.test
          echo "MARIADB_PORT=3306" >> .env.test
          echo "MARIADB_HOST=${{ secrets.MARIADB_HOST_TEST }}" >> .env.test
          echo "MARIADB_USERNAME=${{ secrets.MARIADB_USERNAME_TEST }}" >> .env.test
          echo "MARIADB_PASSWORD=${{ secrets.MARIADB_PASSWORD_TEST }}" >> .env.test
          echo "MONGODB_IMAGE_HOST=${{ secrets.MONGODB_IMAGE_HOST_TEST }}" >> .env.test
          echo "MONGODB_IMAGE_NAME=${{ secrets.MONGODB_IMAGE_NAME_TEST }}" >> .env.test
          echo "MONGODB_IMAGE_PORT=27017" >> .env.test
          echo "MONGODB_IMAGE_USERNAME=${{ secrets.MONGODB_IMAGE_USERNAME_TEST }}" >> .env.test
          echo "MONGODB_IMAGE_PASSWORD=${{ secrets.MONGODB_IMAGE_PASSWORD_TEST }}" >> .env.test
          npm install
      - name: Test e2e
        run: cd ./packages/api && npm run test:e2e
