name: PipelineApp

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: '20'
      - name: Install dependencies
        run: cd ./packages/app && npm install
      - name: Test
        run: cd ./packages/app && npm run test
